version: '2'
services:
  ixo-web:
    environment:
      - PORT=80
    ports:
      - '80:80'
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '1'
